name: SkyBattle-Core
version: '${project.version}'
main: canyonnetwork.net.skybattlecore.Main
api-version: 1.19
authors: [ Someone, FroostySnoowman ]
description: The core plugin for the CanyonNetwork SkyBattle development.
website: canyonnetwork.com
commands:
  test:
    description: Testing commands
    usage: /<command>
